BASE_DIR <- getwd()
print('Execution Start!')
print("Testing the Dockerfile in 'R'anjith")
print(BASE_DIR)
print(paste0(BASE_DIR, "/Data/input.csv"))
df <- read.csv(paste0(BASE_DIR, "/Data/input.csv"), header=TRUE)
print('Input CSV Dataframe:')
#Print a single line space
cat("\n")
print(df)
df2 <- rbind(df,df)
print('Output CSV Combined Dataframes:')
cat("\n")
print(df2)
write.csv(df2, paste0(BASE_DIR, "/Data/output.csv"))
print('Execution Complete!')